apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probes
  name: probes
  namespace: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes
  strategy: {}
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
      - image: mhausenblas/simpleservice:0.5.0
      # https://github.com/mhausenblas/simpleservice
        name: simpleservice
        resources:
          limits:
            memory: "200Mi"
        volumeMounts:
        - name: probes
          mountPath: "/probes"
          readOnly: true  
      volumes:
        - name: probes
          configMap:
            name: probes
status: {}
